# fly.toml app configuration file generated for sql-chatbot on 2023-05-30T00:16:00+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "sql-chatbot"
primary_region = "ams"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
